import { ThemeProvider } from "@/components/formComponents/providers/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import DesignerContextProvider from "@/components/formComponents/context/DesignerContext";
import NextTopLoader from "nextjs-toploader";
import { AuthProvider } from "@/context/AuthProvider";
import { PrivilegesProvider } from "@/context/PrivilegeContext";

const poppins = Poppins({
  weight: ["400", "700"], // Specify the weights you need
  style: ["normal", "italic"], // Specify the styles you need
  subsets: ["latin"], // Correct usage of the subsets property
});

export const metadata: Metadata = {
  title: "Feebify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <ClerkProvider>
        <html lang="en">
          <body className={poppins.className}>
            <NextTopLoader />
            <DesignerContextProvider>
              <PrivilegesProvider>{children}</PrivilegesProvider>
              <Toaster />
            </DesignerContextProvider>
          </body>
        </html>
      </ClerkProvider>
    </AuthProvider>
  );
}
